services:
    Enhavo\Bundle\MultiTenancyBundle\Menu\SwitchTenantMenu:
        arguments:
            - '@Enhavo\Bundle\MultiTenancyBundle\Tenant\TenantManager'
            - '@security.authorization_checker'
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\MultiTenancyBundle\Controller\MultiTenancyController:
        arguments:
            - '@Enhavo\Bundle\MultiTenancyBundle\Tenant\TenantManager'
            - '%enhavo_multi_tenancy.tenant_switch_menu.session_key%'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: controller.service_arguments }
            - { name: container.service_subscriber }
